services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vendorsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - vendors-network

  mock-service:
    image: mockserver/mockserver
    ports:
      - "1080:1080"
    volumes:
      - ./mock/init.json:/config/init.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: "/config/init.json"
    command: "-serverPort 1080"
    networks:
      - vendors-network

networks:
  vendors-network:
    driver: bridge