services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: vendorsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - vendors-network

  mock-service:
    image: mockserver/mockserver
    ports:
      - "1080:1080"
    volumes:
      - ./mock/init.json:/config/init.json
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: "/config/init.json"
    command: "-serverPort 1080"
    networks:
      - vendors-network

  prometheus:
    image: prom/prometheus:v2.44.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

networks:
  vendors-network:
    driver: bridge