spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vendorsdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mock:
  url: http://localhost:1080